"""initial migration

Revision ID: 9e419ee6ae62
Revises: 
Create Date: 2026-02-12 03:16:50.993052

"""
from typing import Sequence, Union

from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e419ee6ae62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('previous_station_id', sa.Integer(), nullable=True),
    sa.Column('next_station_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['next_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['previous_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_line_id'), 'stations', ['line_id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_table('found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('found_date', sa.Date(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_found_items_embedding', 'found_items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('lost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('loss_date', sa.Date(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('is_taken', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_items_status'), 'lost_items', ['status'], unique=False)
    op.create_index('ix_lost_items_status_created', 'lost_items', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('transfer_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id_1', sa.Integer(), nullable=False),
    sa.Column('station_id_2', sa.Integer(), nullable=False),
    sa.Column('line_id_1', sa.Integer(), nullable=False),
    sa.Column('line_id_2', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.Column('transfer_time_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('is_wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['line_id_1'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['line_id_2'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['station_id_1'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_id_2'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id_1', 'station_id_2', name='unique_transfer')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.id'], ),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index('ix_unique_match', 'matches', ['lost_item_id', 'found_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_match', table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('transfer_points')
    op.drop_index('ix_lost_items_status_created', table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_status'), table_name='lost_items')
    op.drop_table('lost_items')
    op.drop_index('ix_found_items_embedding', table_name='found_items', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('found_items')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_line_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_table('users')
    op.drop_table('lines')
    # ### end Alembic commands ###
